# Generated by Django 3.0.6 on 2020-05-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='static/images/products')),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_desc', models.TextField(blank=True, max_length=500)),
                ('p_price', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('p_category', models.CharField(blank=True, max_length=100)),
                ('supplier_name', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
