# Generated by Django 3.0.6 on 2020-05-08 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
