# Generated by Django 3.0.6 on 2020-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200508_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_image',
            field=models.FileField(upload_to='static/images/products'),
        ),
    ]
