# Generated by Django 3.0.6 on 2020-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
